name = "my-app"
compatibility_date = "2024-08-30"
node_compat = true
main = "src/index.ts"

[site]
bucket = "./public"

[ai]
binding = "AI"

[vars]
JWT_SECRET = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
